## two containers
Vagrant.configure("2") do |config|
  config.vm.define "nginx" do |config|
   config.vm.provider "docker" do |d1|
     d1.image = "nginx"
     d1.name = "webb1"
     d1.ports = ["8087:80"]
   end
  end
  config.vm.define "wordpress" do |config|
   config.vm.provider "docker" do |d2|
     d2.image = "wordpress"
     d2.name = "webb2"
     d2.ports = ["8088:80"]
   end
  end
 end